package net.digitalid.core.error;

import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.annotation.Nonnull;
import net.digitalid.core.annotations.NonCommitting;
import net.digitalid.core.annotations.Pure;
import net.digitalid.core.database.Database;
import net.digitalid.core.entity.Site;
import net.digitalid.core.handler.Action;
import net.digitalid.core.module.ClientModule;
import net.digitalid.core.service.CoreService;
import net.digitalid.core.service.Service;

/**
 * This class provides database access to the errors generated by the core service.
 * 
 * @author Kaspar Etter (kaspar.etter@digitalid.net)
 * @version 0.0
 */
public final class ErrorModule implements ClientModule {
    
    /**
     * Stores an instance of this module.
     */
    public static final ErrorModule MODULE = new ErrorModule();
    
    @Pure
    @Override
    public @Nonnull Service getService() {
        return CoreService.SERVICE;
    }
    
    @Override
    @NonCommitting
    public void createTables(@Nonnull Site site) throws SQLException {
        try (@Nonnull Statement statement = Database.createStatement()) {
            // TODO: Create the tables of this module.
        }
    }
    
    @Override
    @NonCommitting
    public void deleteTables(@Nonnull Site site) throws SQLException {
        try (@Nonnull Statement statement = Database.createStatement()) {
            // TODO: Delete the tables of this module.
        }
    }
    
    
    /**
     * Stores the date formatter for the output.
     */
    private static final @Nonnull ThreadLocal<DateFormat> formatter = new ThreadLocal<DateFormat>() {
        @Override protected DateFormat initialValue() {
            return new SimpleDateFormat("yyyy-MM-dd 'at' HH:mm:ss: ");
        }
    };
    
    /**
     * Adds the given message and action to the list of errors.
     * 
     * @param message the message to be added.
     * @param action the action to be added.
     */
    public static void add(@Nonnull String message, @Nonnull Action action) {
        // TODO: Make a real implementation.
//        Logger.log(Level.WARNING, "ErrorModule", message + " '" + action + "'.");
    }
    
    static { CoreService.SERVICE.add(MODULE); }
    
}
