/*
 * Copyright (C) 2017 Synacts GmbH, Switzerland (info@synacts.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// TODO

//package net.digitalid.core.error;
//
//import java.sql.Statement;
//import java.text.DateFormat;
//import java.text.SimpleDateFormat;
//
//import javax.annotation.Nonnull;
//
//import net.digitalid.utility.annotations.method.Pure;
//import net.digitalid.utility.validation.annotations.type.Stateless;
//
//import net.digitalid.database.annotations.transaction.NonCommitting;
//import net.digitalid.database.core.table.Site;
//import net.digitalid.database.interfaces.Database;
//
//import net.digitalid.core.handler.Action;
//import net.digitalid.core.service.CoreService;
//import net.digitalid.core.state.ClientModule;
//import net.digitalid.core.state.Service;
//
///**
// * This class provides database access to the errors generated by the core service.
// */
//@Stateless
//public final class ErrorModule implements ClientModule {
//    
//    /**
//     * Stores an instance of this module.
//     */
//    public static final ErrorModule MODULE = new ErrorModule();
//    
//    @Pure
//    @Override
//    public @Nonnull Service getService() {
//        return CoreService.SERVICE;
//    }
//    
//    @Override
//    @NonCommitting
//    public void createTables(@Nonnull Site site) throws DatabaseException {
//        try (@Nonnull Statement statement = Database.createStatement()) {
//            // TODO: Create the tables of this module.
//        }
//    }
//    
//    @Override
//    @NonCommitting
//    public void deleteTables(@Nonnull Site site) throws DatabaseException {
//        try (@Nonnull Statement statement = Database.createStatement()) {
//            // TODO: Delete the tables of this module.
//        }
//    }
//    
//    
//    /**
//     * Stores the date formatter for the output.
//     */
//    private static final @Nonnull ThreadLocal<DateFormat> formatter = new ThreadLocal<DateFormat>() {
//        @Override protected DateFormat initialValue() {
//            return new SimpleDateFormat("yyyy-MM-dd 'at' HH:mm:ss: ");
//        }
//    };
//    
//    /**
//     * Adds the given message and action to the list of errors.
//     * 
//     * @param message the message to be added.
//     * @param action the action to be added.
//     */
//    public static void add(@Nonnull String message, @Nonnull Action action) {
//        // TODO: Make a real implementation.
////        Log.warning(message + " '" + action + "'.");
//    }
//    
//    static { CoreService.SERVICE.add(MODULE); }
//    
//}
