package net.digitalid.core.settings;

import javax.annotation.Generated;
import javax.annotation.Nonnull;

import net.digitalid.utility.annotations.method.Pure;
import net.digitalid.utility.collaboration.annotations.TODO;
import net.digitalid.utility.collaboration.enumerations.Author;
import net.digitalid.utility.conversion.converters.StringConverter;
import net.digitalid.utility.generator.annotations.generators.GenerateConverter;
import net.digitalid.utility.generator.annotations.generators.GenerateSubclass;
import net.digitalid.utility.validation.annotations.generation.Recover;
import net.digitalid.utility.validation.annotations.size.MaxSize;
import net.digitalid.utility.validation.annotations.type.Immutable;

import net.digitalid.database.annotations.transaction.NonCommitting;
import net.digitalid.database.annotations.type.Embedded;
import net.digitalid.database.auxiliary.None;
import net.digitalid.database.property.value.WritablePersistentValueProperty;

import net.digitalid.core.concept.ConceptModule;
import net.digitalid.core.concept.ConceptModuleBuilder;
import net.digitalid.core.concept.CoreConcept;
import net.digitalid.core.entity.NonHostEntity;
import net.digitalid.core.entity.NonHostEntityConverter;
import net.digitalid.core.identification.identity.SemanticType;
import net.digitalid.core.property.value.SynchronizedValuePropertyTable;
import net.digitalid.core.property.value.SynchronizedValuePropertyTableBuilder;
import net.digitalid.core.property.value.ValuePropertyRequiredAuthorization;
import net.digitalid.core.property.value.ValuePropertyRequiredAuthorizationBuilder;
import net.digitalid.core.property.value.WritableSynchronizedValuePropertyBuilder;
import net.digitalid.core.restrictions.Restrictions;
import net.digitalid.core.restrictions.RestrictionsBuilder;

/**
 * This class models the settings of a digital identity.
 */
@Immutable
@GenerateSubclass
@GenerateConverter
public abstract class Settings extends CoreConcept<NonHostEntity, None> {
    
    @Pure
    @Override
    @Embedded // TODO: Depends on the key type!
    @TODO(task = "Why aren't the annotations inherited and included in the generated converter otherwise? (Remove this method once this issue is fixed.)", date = "2016-11-14", author = Author.KASPAR_ETTER)
    public abstract @Nonnull None getKey();
    
    /* -------------------------------------------------- Index -------------------------------------------------- */
    
    @Generated("TODO in Subclass") // TODO: This should be generated by the '@GenerateConceptModule' annotation in the subclass.
    static final @Nonnull ConceptModule<NonHostEntity, None, Settings> MODULE = ConceptModuleBuilder.<NonHostEntity, None, Settings>withName("Settings").withService(SERVICE).withConceptFactory(SettingsSubclass::new).withEntityConverter(NonHostEntityConverter.INSTANCE).withConceptConverter(SettingsConverter.INSTANCE).build();
    
    @Pure
    @Override
    @Generated("TODO in Subclass") // TODO: This should be generated by the '@GenerateConceptModule' annotation in the subclass.
    public @Nonnull ConceptModule<NonHostEntity, None, Settings> getConceptModule() {
        return MODULE;
    }
    
    /**
     * Returns the potentially cached settings of the given entity that might not yet exist in the database.
     */
    @Pure
    @Recover
    @NonCommitting
    public static @Nonnull Settings of(@Nonnull NonHostEntity entity) {
        return SettingsSubclass.MODULE.getConceptIndex().get(entity, None.INSTANCE);
    }
    
    /* -------------------------------------------------- Value Property -------------------------------------------------- */
    
    /**
     * Stores the required authorization to change the password.
     */
    static final @Nonnull ValuePropertyRequiredAuthorization<NonHostEntity, None, Settings, String> PASSWORD_AUTHORIZATION = ValuePropertyRequiredAuthorizationBuilder.<NonHostEntity, None, Settings, String>withRequiredRestrictionsToExecuteMethod((concept, value) -> RestrictionsBuilder.withOnlyForClients(true).withWriteToNode(true).build()).withRequiredRestrictionsToSeeMethod((concept, value) -> Restrictions.ONLY_FOR_CLIENTS).build();
    
    @Generated("TODO in Subclass") // TODO: This should be generated by the '@GenerateSynchronizedProperty' annotation in the subclass.
    /* TODO: Make it private. (The test case has to create the table manually so far.) */ static final @Nonnull SynchronizedValuePropertyTable<NonHostEntity, None, Settings, @Nonnull @MaxSize(50) String, Void> PASSWORD_TABLE = SynchronizedValuePropertyTableBuilder.<NonHostEntity, None, Settings, String, Void>withName("password").withValueConverter(StringConverter.INSTANCE).withDefaultValue("").withParentModule(MODULE).withRequiredAuthorization(PASSWORD_AUTHORIZATION).withActionType(SemanticType.map("password.settings@core.digitalid.net")).withValueValidator(password -> password.length() <= 50).build();
    
    @Generated("TODO in Subclass") // TODO: This should be generated by the '@GenerateSynchronizedProperty' annotation in the subclass.
    private final @Nonnull WritablePersistentValueProperty<Settings, @Nonnull @MaxSize(50) String> password = WritableSynchronizedValuePropertyBuilder.<NonHostEntity, None, Settings, String>withConcept(this).withTable(PASSWORD_TABLE).build();
    
    /**
     * Stores the password of these settings.
     */
    @Pure
//    @Default("\"\"") // TODO: "The generation annotation may only be used on abstract getters."
    @Generated("TODO in Subclass") // TODO: Only the abstract method should be declared here.
//    @GenerateSynchronizedProperty // TODO: Only allowed on abstract methods.
    public @Nonnull WritablePersistentValueProperty<Settings, @Nonnull @MaxSize(50) String> password() {
        return password;
    }
    
}
