package ch.virtualid.error;

import ch.virtualid.annotations.Pure;
import ch.virtualid.database.Database;
import ch.virtualid.entity.Site;
import ch.virtualid.handler.Action;
import ch.virtualid.module.ClientModule;
import ch.virtualid.service.CoreService;
import ch.virtualid.service.Service;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.annotation.Nonnull;

/**
 * This class provides database access to the errors generated by the core service.
 * 
 * @author Kaspar Etter (kaspar.etter@virtualid.ch)
 * @version 0.0
 */
public final class ErrorModule implements ClientModule {
    
    /**
     * Stores an instance of this module.
     */
    public static final ErrorModule MODULE = new ErrorModule();
    
    @Pure
    @Override
    public @Nonnull Service getService() {
        return CoreService.SERVICE;
    }
    
    @Override
    public void createTables(@Nonnull Site site) throws SQLException {
        try (@Nonnull Statement statement = Database.createStatement()) {
            // TODO: Create the tables of this module.
        }
    }
    
    @Override
    public void deleteTables(@Nonnull Site site) throws SQLException {
        try (@Nonnull Statement statement = Database.createStatement()) {
            // TODO: Delete the tables of this module.
        }
    }
    
    
    /**
     * Stores the date formatter for the output.
     */
    private static final @Nonnull ThreadLocal<DateFormat> formatter = new ThreadLocal<DateFormat>() {
        @Override protected DateFormat initialValue() {
            return new SimpleDateFormat("yyyy-MM-dd 'at' HH:mm:ss: ");
        }
    };
    
    /**
     * Adds the given message and action to the list of errors.
     * 
     * @param message the message to be added.
     * @param action the action to be added.
     */
    public static void add(@Nonnull String message, @Nonnull Action action) {
        // TODO: Make a real implementation.
        System.err.println(formatter.get().format(new Date()) + message + " '" + action + "'.");
    }
    
    static { CoreService.SERVICE.add(MODULE); }
    
}
